version: '3'
services:
    web:
        build: .
        ports:
            - "2222:22"
        command: /bin/sh /app/script.sh
    web1:
        image: grafana/grafana
        ports:
            - "3000:3000"

