version: '3'
services:
    honeypot:
        build: .
        ports:
            - "2222:22"
        command: /bin/sh /app/script.sh
    web:
        image: grafana/grafana
        ports:
            - "3000:3000"
    db:
        image: influxdb

